// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ShimmerSample
{
	public partial class ShimmeringView : Plugin.Shimmer.iOS.FBShimmeringView
	{
		public ShimmeringView (IntPtr handle) : base (handle)
		{
		}
	}
}
